# Generated by Django 5.2.1 on 2025-06-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_seat_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.showtime'),
            preserve_default=False,
        ),
    ]
