# Generated by Django 5.2.1 on 2025-06-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
