# Generated by Django 5.2.1 on 2025-06-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_booking_seat_alter_booking_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
