# Generated by Django 5.2.1 on 2025-06-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_showtime_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6),
        ),
    ]
